const FETCH_CARS = 'FETCH_CARS';
const CREATE_CARS = 'CREATE_CARS';
const FETCH_CARS_BY_ID = 'FETCH_CARS_BY_ID';
const DELETE_CAR = 'DELETE_CAR';
export {FETCH_CARS, CREATE_CARS, FETCH_CARS_BY_ID, DELETE_CAR}