const FETCH_CARS = 'FETCH_CARS';
const CREATE_CAR = 'CREATE_CAR';
const FETCH_CARS_BY_ID = 'FETCH_CARS_BY_ID';
const DELETE_CAR = 'DELETE_CAR';
export {FETCH_CARS, CREATE_CAR, FETCH_CARS_BY_ID, DELETE_CAR}